#!/bin/bash
 
# Invoke the Forever module (to START our Node.js server).

sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8080


PORT=8080 \
NODE_ENV=production \
DB_URI=mongodb://localhost/strider \
SERVER_NAME=http://ec2-54-246-42-0.eu-west-1.compute.amazonaws.com \
GITHUB_APP_ID=071b43d34cdeede50a7e \
GITHUB_APP_SECRET=34cfc60908824e4c6af31fdfc279ef785af65b36 \
./node_modules/forever/bin/forever \
start \
-al forever.log \
-ao out.log \
-ae err.log \
bin/strider